name: Linting

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7
